### PR TITLE
Switch calculations to mapshaper

### PR DESCRIPTION
**Pull request by beamalsky**
@pjsier After 1.5 months I've finally picked this up! The `mapshaper` approach is a great one. Thank you for the PR. I've rewritten everthing here to use this new data building method, and when I run it locally the site is super fast. 

The impetus here is that I'm planning to add a feature to the time series bar chart where you can filter it by neighborhood through a dropdown, and having all this data work in a Makefile should make that way easier to set up. The action here is failing because there are no changes to `cases.json` to submit, but the deploy preview passes and much speedier: https://5ee5aaf6af42650008d35f95--cc-covid-medical-examiner.netlify.app/

Pat, I'd love your input here if you have a chance. One quirk of this is that I couldn't get `gatsby-transformer-geojson` to recognize the `geometry` field of any of the geojson generated by mapshaper, which is why all the output there is saved as json. I think that's actually fine in this case, but a limitation it would be cool to find a way around.

### CODE REVIEW

**Comment by pjsier** [comment]
@beamalsky thanks for making these updates! When I build it locally it looks like the cases mapshaper builds have some `null` geometries, and I'm guessing that's why the GeoJSON transformer isn't working. Do you think it's better to set them to 0,0 to use the GeoJSON transformer or to use the JSON as is?

**Comment by beamalsky** [comment]
It would be better to be able to use the geojson transformer for everything, so we could put the community area geometries and the counts in one file! Is there a way to avoid setting null values in mapshaper @pjsier?

**Comment by pjsier** [comment]
@beamalsky do you mean leaving off the `geometry` property or something else? I think the transformer requires a `geometry` key either way, and it looks like the cases with null geometries don't have coordinates supplied

**Comment by beamalsky** [comment]
Let me try to explain the problem better. If I generate `community_areas_cases.geojson` instead of `community_areas_cases.json` in the Makefile and try to load it in with `gatsby-transformer-geojson`, I get this error:

```
warn There are conflicting field types in your data.

If you have explicitly defined a type for those fields, you can safely ignore this
warning message.
Otherwise, Gatsby will omit those fields from the GraphQL schema.

If you know all field types in advance, the best strategy is to explicitly define them
GeoJson.features.geometry.coordinates:
 - type: [array]
   value: [ ..., [ ..., -87.60914087617894, ... ], ... ]
 - type: [number]
   value: [ ..., -87.60914087617894, ... ]
```

I'm able to use my community areas boundary file `chicago_community_areas.geojson` just fine, and in this PR I source from both that and `community_areas_cases.json` in `gatsby-config` and then combine there here, which is an ok workaround but not ideal.

Do you know why `community_areas_cases.geojson` would be throwing that error? I've tried various `mapshaper` flags but wasn't able to change anything. Here's how it's made, from your code:

```
src/data/community_areas_cases.geojson: src/data/chicago_community_areas.geojson src/data/cases_filtered.geojson
	mapshaper -i $< \
	-join $(filter-out $<,$^) calc 'value = count()' \
	-filter-fields community,value \
	-o $@ format=geojson
```

My fear is that it's a limitation of `gatsby-transformer-geojson`, which doesn't have much documentation, but I'm not sure exactly what's going on.

**Comment by pjsier** [comment]
I think I get what you mean now, thanks for clarifying! I was looking at the points instead of the areas. It looks like the issue is that the original community area geometries are all MultiPolygons, but mapshaper simplifies them to Polygons except for O'Hare because it has the tiny disconnected piece. That makes the `coordinates` property a different type in O'Hare vs all the other areas and causes the error

Adding `-filter-islands` to the original processing command removes that tiny sliver and fixes it:

```shell
mapshaper -i $< \
-join $(filter-out $<,$^) calc 'value = count()' \
-filter-islands min-area=1km2 \
-filter-fields community,value \
-o $@ format=geojson
```

Quick caveat on this is that it only fixes it if you're pulling from one GeoJSON file at a time and not both, otherwise it gets confused and tries to load all coordinates at the same time and triggers the original error.

And I took a quick look at the GeoJSON transformer after you mentioned it, and I think it might be fine to remove here. It seems like the only benefit it has is converting the type in GraphQL to make it more strict, but not sure if that's much of a pro

**Comment by beamalsky** [comment]
Oh nice debugging!! Let me see if I can get it working now. It'd be nice to have `community_areas_cases.geojson` as a geojson so that I don't need the loop [here](https://github.com/beamalsky/medical-examiner-data/pull/48/files#diff-213cf7e2e65337d6ee14b8cb7e01807fR44) where I combine the community area geometries with the calculated counts.

**Comment by beamalsky** [comment]
It worked! I don't love the limitation of only being able to load in one geojson file in `gatsby-config`, but for this app that shouldn't be a problem. Thank you Pat! I'm going to merge this in if the preview looks good.

**Pull request merged**
